### PR TITLE
Fix: Add support for authoring tool 1 (fixes #39)

### LINKED ISSUE #39: Add support for authoring tool v1
As per core issue https://github.com/adaptlearning/adapt_framework/issues/2704

### PR DESCRIPTION
**Pull request by joe-replin**
Fixes: #39 

### Fix
* Added new schema files

### CODE REVIEW

**Comment by joe-replin** [comment]
Note: Unable to test this in https://testing.kineoadapt.com/ at this time due to not being able to upload new versions of plug-ins.

**Comment by joe-replin** [comment]
Tested in the AAT environment. Schemas ready to go.

**Comment by swashbuck** [comment]
Looks good.  Some suggestions for tooltips (feel free to reword):

**Icon class**
Show a tooltip with suggested icon and/or use the instructions from the readme?  Ideally, include the Wiki URL somehow ( https://github.com/adaptlearning/adapt-contrib-vanilla/wiki/Icons ) _but_ you can't click on links within a tooltip.

> CSS class name to be applied to the button icon. Suggested: icon-home

**_alignIconright**
Add tooltip like "Defines whether the icon is aligned to the left or right of the text."

**Text** for each button
Maybe rename this to "Button text"? Then, mention in a tooltip that it's optional and you can only use an icon if that's your jam.

**Override the route id**
Add a tooltip.

> "Overrides the route ID. For use when non standard route navigation is required."

These are the instructions from the readme, but I think it could be dumbed down for non-devs.  For instance, mention that it should correspond to a page's Friendly id (I assume that's the case).

**Review by swashbuck — APPROVED** [review]
👍

**Pull request merged**
